### ISSUE TITLE
Bugs in "profile.php"

### ISSUE THREAD

**Issue by youthinkk** [cs2102-group2/main#22]
# Bugs
#### Duplicate Pending Rides

There are duplicate time slots. For example, the first and third entry of following screenshot are the same. (Unless it is set that the account holder takes two seats)

<img width="839" alt="2102_profile_php_conflict_of_time" src="https://cloud.githubusercontent.com/assets/13010884/10846133/3662974e-7f48-11e5-8c32-43ea5f5923f8.png">

**Comment by MunKeat** [comment]
Duplicate trips should be resolved due to the definition of the Bookings Table.
